graph TD
    IMG[Image]
    TXT[Text]

    subgraph "SAIC"
        subgraph "Semantic Saliency Module"
            subgraph "Semantic Understanding"
                DINO("Grounding DINO")
                BB(["Bounding Box"])
            end

            subgraph "Segmentation"
                SAM("SAM")
                M(["Saliency Map"])
            end
        end

        subgraph "Spatial Compression Module"
        X(["$$x$$"])
        Y(["$$y$$"])
        Y_HAT(["$$\hat y$$"])

        CONC("Concatenate")
        Q("Quantizer")
        GA("Analysis Transform")
        GS("Synthesis Transform")
        MC("Masked Convolution")
        CNET("1x1 Conv")

            subgraph "Hyperlatent Module"
            HA("Hyper-Analysis Transform")
            HQ("Hyper-Quantizer")
            HS("Hyper-Synthesis Transform")
            HE("Hyper-Entropy Model")

            Z(["$$z$$"])
            Z_HAT(["$$\hat z$$"])

            end

        MS(["$$\mu , \sigma$$"])
        E("Entropy Model")
        end
    end

X_HAT(["$$\hat x$$"])
RZ(["$$R_{\hat z}$$"])
RY(["$$R_{\hat y}$$"])

%% ===================
%% ===== MASKING =====
%% ===================

%% DINO creates bounding boxes from image and text, which are then segmented by SAM
IMG --> DINO;
TXT --> DINO;
DINO --> BB;
BB --> SAM;
SAM --> M;

%% =======================
%% ===== COMPRESSION =====
%% =======================

%% Image and saliency map are concatenated into a 4 channel image tensor
IMG --> CONC;
M --> CONC;
CONC --> X;

%% x is passed through the analysis transform
%% y is then quantized into y_hat
%% y_hat passes through the entropy model
%% y_hat is reconstructed into x_hat using the synthesis transform
X --> GA;
GA --> Y;
Y --> Q;
Q --> Y_HAT;

%% We also run masked convolution on y_hat 
%% And then joint convolution with synthesized z
%% to predict mu and sigma that will help our entropy model
%% (local context)
Y_HAT --> MC;
HS --> CNET;
MC --> CNET;

%% This local context model combined with the hyperprior allows for estimation
%% of pdf parameters
CNET --> MS;
Y_HAT --> E;
MS --> E;

E --> GS;
GS --> X_HAT;

E --> RY

%% ======================
%% ===== HYPERPRIOR =====
%% ======================

%% y is passed through the hyper network to find z, which is quantized to z_hat
Y --> HA;
HA --> Z
Z --> HQ;
HQ --> Z_HAT;

%% Rz is found with the hyper entropy model
Z_HAT --> HE;
HE --> RZ;

%% Synthesize z
Z_HAT --> HS;